[package]
name = "NtHiM"
version = "0.0.2"
authors = ["Binit Ghimire <thebinitghimire@gmail.com>"]
edition = "2018"
license = "MIT"
categories = ["command-line-utilities"]
description = "Now, the Host is Mine! - Super Fast Sub-domain Takeover Detection!"
homepage = "https://whoisbinit.me/NtHiM/"
documentation = "https://whoisbinit.me/NtHiM/"
repository = "https://github.com/TheBinitGhimire/NtHiM/"
readme = "README.md"
keywords = ["host-takeover", "subdomain-takeover", "domain-takeover", "subdomain-takeovers", "dangling-dns", "penetration-testing", "pentesting", "pentest", "bug-bounty", "bug-bounties"]
exclude = [".git/*", "target/*", "docs/*"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = ""
clap = "3.0.0-beta.2"
futures = ""
reqwest = "0.10.0"
serde = ""
serde_derive = ""
serde_json = ""
tokio = { version = "0.2", features = ["full"] }